Resources:
  usersTable:
      Type: AWS::DynamoDB::Table
      Properties: 
        TableName: ${self:provider.stage}-${self:service}-users
        BillingMode: PAY_PER_REQUEST
        AttributeDefinitions:
          - AttributeName: "id"
            AttributeType: "S"
          - AttributeName: "phoneNumber"
            AttributeType: "S"
        KeySchema: 
          - AttributeName: "id"
            KeyType: "HASH"
        GlobalSecondaryIndexes:
          - IndexName: phone-index
            KeySchema: 
              - AttributeName: "phoneNumber"
                KeyType: "HASH"
            Projection: 
              ProjectionType: ALL
        Tags:
          - Key: Stage
            Value: ${self:provider.stage}
          - Key: Service
            Value: ${self:service}
  classesTable:
      Type: AWS::DynamoDB::Table
      Properties: 
        TableName: ${self:provider.stage}-${self:service}-classes
        BillingMode: PAY_PER_REQUEST
        AttributeDefinitions:
          - AttributeName: "id"
            AttributeType: "S"
          - AttributeName: "date"
            AttributeType: "S"
        KeySchema: 
          - AttributeName: "id"
            KeyType: "HASH"
        GlobalSecondaryIndexes:
          - IndexName: date-index
            KeySchema: 
              - AttributeName: "date"
                KeyType: "HASH"
            Projection: 
              ProjectionType: ALL
        Tags:
          - Key: Stage
            Value: ${self:provider.stage}
          - Key: Service
            Value: ${self:service}
  packagesTable:
      Type: AWS::DynamoDB::Table
      Properties: 
        TableName: ${self:provider.stage}-${self:service}-packages
        BillingMode: PAY_PER_REQUEST
        AttributeDefinitions:
          - AttributeName: "id"
            AttributeType: "S"
        KeySchema: 
          - AttributeName: "id"
            KeyType: "HASH"
        Tags:
          - Key: Stage
            Value: ${self:provider.stage}
          - Key: Service
            Value: ${self:service}