Resources:
  usersTable:
      Type: AWS::DynamoDB::Table
      Properties: 
        TableName: ${self:provider.stage}-${self:service}-users
        BillingMode: PAY_PER_REQUEST
        AttributeDefinitions:
          - AttributeName: "phoneNumber"
            AttributeType: "S"
        KeySchema: 
          - AttributeName: "phoneNumber"
            KeyType: "HASH"
        Tags:
          - Key: Stage
            Value: ${self:provider.stage}
          - Key: Service
            Value: ${self:service}
  classesTable:
      Type: AWS::DynamoDB::Table
      Properties: 
        TableName: ${self:provider.stage}-${self:service}-classes
        BillingMode: PAY_PER_REQUEST
        AttributeDefinitions:
          - AttributeName: "month"
            AttributeType: "S"
          - AttributeName: "date"
            AttributeType: "S"
        KeySchema: 
          - AttributeName: "month"
            KeyType: "HASH"
          - AttributeName: "date"
            KeyType: "RANGE"
        Tags:
          - Key: Stage
            Value: ${self:provider.stage}
          - Key: Service
            Value: ${self:service}
  packagesTable:
      Type: AWS::DynamoDB::Table
      Properties: 
        TableName: ${self:provider.stage}-${self:service}-packages
        BillingMode: PAY_PER_REQUEST
        AttributeDefinitions:
          - AttributeName: "id"
            AttributeType: "S"
        KeySchema: 
          - AttributeName: "id"
            KeyType: "HASH"
        Tags:
          - Key: Stage
            Value: ${self:provider.stage}
          - Key: Service
            Value: ${self:service}