Resources:
  usersTable:
      Type: AWS::DynamoDB::Table
      Properties: 
        TableName: ${self:provider.stage}-${self:service}-users
        BillingMode: PAY_PER_REQUEST
        AttributeDefinitions:
          - AttributeName: "phoneNumber"
            AttributeType: "S"
          - AttributeName: "email"
            AttributeType: "S"
        KeySchema: 
          - AttributeName: "phoneNumber"
            KeyType: "HASH"
        GlobalSecondaryIndexes:
          - IndexName: email-index
            KeySchema: 
              - AttributeName: "email"
                KeyType: "HASH"
            Projection: 
              ProjectionType: ALL
        Tags:
          - Key: Stage
            Value: ${self:provider.stage}
          - Key: Service
            Value: ${self:service}
  classesTable:
      Type: AWS::DynamoDB::Table
      Properties: 
        TableName: ${self:provider.stage}-${self:service}-classes
        BillingMode: PAY_PER_REQUEST
        AttributeDefinitions:
          - AttributeName: "month"
            AttributeType: "S"
          - AttributeName: "date"
            AttributeType: "S"
        KeySchema: 
          - AttributeName: "month"
            KeyType: "HASH"
          - AttributeName: "date"
            KeyType: "RANGE"
        Tags:
          - Key: Stage
            Value: ${self:provider.stage}
          - Key: Service
            Value: ${self:service}
  classesTableV2:
      Type: AWS::DynamoDB::Table
      Properties: 
        TableName: ${self:provider.stage}-${self:service}-classes-v2
        BillingMode: PAY_PER_REQUEST
        AttributeDefinitions:
          - AttributeName: "month"
            AttributeType: "S"
          - AttributeName: "date_by_type"
            AttributeType: "S"
        KeySchema: 
          - AttributeName: "month"
            KeyType: "HASH"
          - AttributeName: "date_by_type"
            KeyType: "RANGE"
        Tags:
          - Key: Stage
            Value: ${self:provider.stage}
          - Key: Service
            Value: ${self:service}
  packagesTable:
      Type: AWS::DynamoDB::Table
      Properties: 
        TableName: ${self:provider.stage}-${self:service}-packages
        BillingMode: PAY_PER_REQUEST
        AttributeDefinitions:
          - AttributeName: "id"
            AttributeType: "S"
        KeySchema: 
          - AttributeName: "id"
            KeyType: "HASH"
        Tags:
          - Key: Stage
            Value: ${self:provider.stage}
          - Key: Service
            Value: ${self:service}
  verificationCodesTable:
      Type: AWS::DynamoDB::Table
      Properties: 
        TableName: ${self:provider.stage}-${self:service}-verification-codes
        BillingMode: PAY_PER_REQUEST
        AttributeDefinitions:
          - AttributeName: "phoneNumber"
            AttributeType: "S"
        KeySchema: 
          - AttributeName: "phoneNumber"
            KeyType: "HASH"
        TimeToLiveSpecification:
          AttributeName: "ttl"
          Enabled: true
        Tags:
          - Key: Stage
            Value: ${self:provider.stage}
          - Key: Service
            Value: ${self:service}
  purchasesTable:
      Type: AWS::DynamoDB::Table
      Properties: 
        TableName: ${self:provider.stage}-${self:service}-purchases
        BillingMode: PAY_PER_REQUEST
        AttributeDefinitions:
          - AttributeName: "id"
            AttributeType: "S"
          - AttributeName: "package_id"
            AttributeType: "S"
          - AttributeName: "purchase_date"
            AttributeType: "S"
        KeySchema: 
          - AttributeName: "id"
            KeyType: "HASH"
        GlobalSecondaryIndexes:
          - IndexName: package_id-index
            KeySchema: 
              - AttributeName: "package_id"
                KeyType: "HASH"
              - AttributeName: "purchase_date"
                KeyType: "RANGE"
            Projection: 
              ProjectionType: ALL
        Tags:
          - Key: Stage
            Value: ${self:provider.stage}
          - Key: Service
            Value: ${self:service}
  forbiddenEmailsTable:
    Type: AWS::DynamoDB::Table
    Properties: 
      TableName: ${self:provider.stage}-${self:service}-forbidden-emails
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: "email"
          AttributeType: "S"
      KeySchema: 
        - AttributeName: "email"
          KeyType: "HASH"
      Tags:
        - Key: Stage
          Value: ${self:provider.stage}
        - Key: Service
          Value: ${self:service}