service: the-studio

configValidationMode: error

plugins: 
  - serverless-plugin-typescript
  - serverless-offline
  - serverless-dynamodb
  - serverless-s3-local
  - serverless-plugin-common-excludes
  - serverless-plugin-include-dependencies

package:
  excludeDevDependencies: false
  individually: true
  
provider: 
  name: aws
  runtime: nodejs18.x
  region: ${opt:region, "us-east-1"}
  stage: ${opt:stage, "local"}
  timeout: 30
  environment:
    STAGE: ${self:provider.stage}
  iam:
    role:
      statements:
        - Effect: Allow
          Action: 
            - dynamodb:Query
            - dynamodb:Scan
            - dynamodb:GetItem
            - dynamodb:PutItem
            - dynamodb:UpdateItem
            - dynamodb:DeleteItem
            - dynamodb:BatchGetItem
            - dynamodb:BatchWriteItem
          Resource: 'arn:aws:dynamodb:us-east-2:*:*'
        - Effect: Allow
          Action: 
            - s3:GetObject
            - s3:PutObject
          Resource: '*'
  apiGateway:
    restApiId: !Ref MainApi
    restApiRootResourceId: !GetAtt MainApi.RootResourceId

resources:
  - '${file(./aws/resources/cloudfront.yaml)}'
  - '${file(./aws/resources/dynamodb.yaml)}'
  - '${file(./aws/resources/s3.yaml)}'
  - '${file(./aws/resources/apigateway.yaml)}'

custom:
  defaults: ${file(./defaults.yaml)}
  tags: ${self:custom.defaults.tags}
  environment: ${self:custom.defaults.environment}
  service: ${self:service}
  base: ${self:service}-${self:provider.stage}
  dynamodb:
    stages:
      - local
    start: 
      port: 4000
      inMemory: true
      migrate: true
      seed: true
    seed:
      tables:
        sources:
          - table: ${self:provider.stage}-${self:service}-users
            sources: [./src/seeds/users.json]
          - table: ${self:provider.stage}-${self:service}-classes
            sources: [./src/seeds/classes.json]
          - table: ${self:provider.stage}-${self:service}-packages
            sources: [./src/seeds/packages.json]
  s3:
    host: localhost
    region: us-east-1
    directory: ./.bucket
    port: 3005

functions:
  registerUser:
      name: ${self:custom.base}-registerUser
      description: 'Registers a new user'
      handler: src/handlers/register.handler
      timeout: 30
      memorySize: 264
      package:
        patterns:
          - '!src/**'
          - 'src/handlers/register.*'
          - 'src/constants.*'
          - 'src/dynamodb/*'
          - 'src/helpers/**/*'
      environment:
        USERS_TABLE: ${self:custom.environment.USERS_TABLE}
      events:
        - http:
            path: /register
            method: post
            cors: true
  login:
      name: ${self:custom.base}-login
      description: 'Logs a user into the app'
      handler: src/handlers/login.handler
      timeout: 30
      memorySize: 264
      package:
        patterns:
          - '!src/**'
          - 'src/handlers/login.*'
          - 'src/constants.*'
          - 'src/dynamodb/*'
          - 'src/helpers/**/*'
      environment:
        USERS_TABLE: ${self:custom.environment.USERS_TABLE}
        JWT_SECRET: ${self:custom.environment.JWT_SECRET}
      events:
        - http:
            path: /login
            method: post
            cors: true
  bookClass:
      name: ${self:custom.base}-bookClass
      description: 'Allows the user to book a class'
      handler: src/handlers/bookClass.handler
      timeout: 30
      memorySize: 264
      package:
        patterns:
          - '!src/**'
          - 'src/handlers/bookClass.*'
          - 'src/constants.*'
          - 'src/dynamodb/*'
          - 'src/helpers/**/*'
      environment:
        USERS_TABLE: ${self:custom.environment.USERS_TABLE}
        CLASSES_TABLE: ${self:custom.environment.CLASSES_TABLE}
        JWT_SECRET: ${self:custom.environment.JWT_SECRET}
      events:
        - http:
            path: /bookClass
            method: post
            cors: true
  cancelClass:
      name: ${self:custom.base}-cancelClass
      description: 'Allows the user and admin to cancel a class'
      handler: src/handlers/cancelClass.handler
      timeout: 30
      memorySize: 264
      package:
        patterns:
          - '!src/**'
          - 'src/handlers/cancelClass.*'
          - 'src/constants.*'
          - 'src/dynamodb/*'
          - 'src/helpers/**/*'
      environment:
        USERS_TABLE: ${self:custom.environment.USERS_TABLE}
        CLASSES_TABLE: ${self:custom.environment.CLASSES_TABLE}
        JWT_SECRET: ${self:custom.environment.JWT_SECRET}
      events:
        - http:
            path: /cancelClass
            method: post
            cors: true
  getUserBookedClasses:
      name: ${self:custom.base}-getUserBookedClasses
      description: 'Allows the user and admin to cancel a class'
      handler: src/handlers/getUserBookedClasses.handler
      timeout: 30
      memorySize: 264
      package:
        patterns:
          - '!src/**'
          - 'src/handlers/getUserBookedClasses.*'
          - 'src/constants.*'
          - 'src/dynamodb/*'
          - 'src/helpers/**/*'
      environment:
        USERS_TABLE: ${self:custom.environment.USERS_TABLE}
        CLASSES_TABLE: ${self:custom.environment.CLASSES_TABLE}
        JWT_SECRET: ${self:custom.environment.JWT_SECRET}
      events:
        - http:
            path: /getUserBookedClasses
            method: get
            cors: true
  getUpcomingClasses:
      name: ${self:custom.base}-getUpcomingClasses
      description: 'Allows the user and admin to cancel a class'
      handler: src/handlers/getUpcomingClasses.handler
      timeout: 30
      memorySize: 264
      package:
        patterns:
          - '!src/**'
          - 'src/handlers/getUpcomingClasses.*'
          - 'src/constants.*'
          - 'src/dynamodb/*'
          - 'src/helpers/**/*'
      environment:
        USERS_TABLE: ${self:custom.environment.USERS_TABLE}
        CLASSES_TABLE: ${self:custom.environment.CLASSES_TABLE}
        JWT_SECRET: ${self:custom.environment.JWT_SECRET}
      events:
        - http:
            path: /getUpcomingClasses
            method: get
            cors: true
  createClasses:
      name: ${self:custom.base}-createClasses
      description: 'Allows the user and admin to cancel a class'
      handler: src/handlers/createClasses.handler
      timeout: 30
      memorySize: 264
      package:
        patterns:
          - '!src/**'
          - 'src/handlers/createClasses.*'
          - 'src/constants.*'
          - 'src/dynamodb/*'
          - 'src/helpers/**/*'
      environment:
        CLASSES_TABLE: ${self:custom.environment.CLASSES_TABLE}
        JWT_SECRET: ${self:custom.environment.JWT_SECRET}
      events:
        - http:
            path: /createClasses
            method: post
            cors: true
  getProfile:
      name: ${self:custom.base}-getProfile
      description: 'Allows the user and admin to cancel a class'
      handler: src/handlers/getProfile.handler
      timeout: 30
      memorySize: 264
      package:
        patterns:
          - '!src/**'
          - 'src/handlers/getProfile.*'
          - 'src/constants.*'
          - 'src/dynamodb/*'
          - 'src/helpers/**/*'
      environment:
        USERS_TABLE: ${self:custom.environment.USERS_TABLE}
        JWT_SECRET: ${self:custom.environment.JWT_SECRET}
      events:
        - http:
            path: /getProfile
            method: get
            cors: true
  getAllPackages:
      name: ${self:custom.base}-getAllPackages
      description: 'Allows the user and admin to cancel a class'
      handler: src/handlers/getAllPackages.handler
      timeout: 30
      memorySize: 264
      package:
        patterns:
          - '!src/**'
          - 'src/handlers/getAllPackages.*'
          - 'src/constants.*'
          - 'src/dynamodb/*'
          - 'src/helpers/**/*'
      environment:
        PACKAGES_TABLE: ${self:custom.environment.PACKAGES_TABLE}
        JWT_SECRET: ${self:custom.environment.JWT_SECRET}
      events:
        - http:
            path: /getAllPackages
            method: get
            cors: true
  addPackageToUser:
      name: ${self:custom.base}-addPackageToUser
      description: 'Allows the user to book a class'
      handler: src/handlers/addPackageToUser.handler
      timeout: 30
      memorySize: 264
      package:
        patterns:
          - '!src/**'
          - 'src/handlers/addPackageToUser.*'
          - 'src/constants.*'
          - 'src/dynamodb/*'
          - 'src/helpers/**/*'
      environment:
        USERS_TABLE: ${self:custom.environment.USERS_TABLE}
        PACKAGES_TABLE: ${self:custom.environment.PACKAGES_TABLE}
        JWT_SECRET: ${self:custom.environment.JWT_SECRET}
      events:
        - http:
            path: /addPackageToUser
            method: post
            cors: true
  getUsers:
      name: ${self:custom.base}-getUsers
      description: 'Allows the user and admin to cancel a class'
      handler: src/handlers/getUsers.handler
      timeout: 30
      memorySize: 264
      package:
        patterns:
          - '!src/**'
          - 'src/handlers/getUsers.*'
          - 'src/constants.*'
          - 'src/dynamodb/*'
          - 'src/helpers/**/*'
      environment:
        USERS_TABLE: ${self:custom.environment.USERS_TABLE}
        JWT_SECRET: ${self:custom.environment.JWT_SECRET}
      events:
        - http:
            path: /getUsers
            method: get
            cors: true
  getClassInfo:
      name: ${self:custom.base}-getClassInfo
      description: 'Allows the user and admin to cancel a class'
      handler: src/handlers/getClassInfo.handler
      timeout: 30
      memorySize: 264
      package:
        patterns:
          - '!src/**'
          - 'src/handlers/getClassInfo.*'
          - 'src/constants.*'
          - 'src/dynamodb/*'
          - 'src/helpers/**/*'
      environment:
        CLASSES_TABLE: ${self:custom.environment.CLASSES_TABLE}
        JWT_SECRET: ${self:custom.environment.JWT_SECRET}
      events:
        - http:
            path: /getClassInfo
            method: get
            cors: true
  getUserInfo:
      name: ${self:custom.base}-getUserInfo
      description: 'Allows the user and admin to cancel a class'
      handler: src/handlers/getUserInfo.handler
      timeout: 30
      memorySize: 264
      package:
        patterns:
          - '!src/**'
          - 'src/handlers/getUserInfo.*'
          - 'src/constants.*'
          - 'src/dynamodb/*'
          - 'src/helpers/**/*'
      environment:
        USERS_TABLE: ${self:custom.environment.USERS_TABLE}
        JWT_SECRET: ${self:custom.environment.JWT_SECRET}
      events:
        - http:
            path: /getUserInfo
            method: get
            cors: true
  getUserClasses:
      name: ${self:custom.base}-getUserClasses
      description: 'Allows the user and admin to cancel a class'
      handler: src/handlers/getUserClasses.handler
      timeout: 30
      memorySize: 264
      package:
        patterns:
          - '!src/**'
          - 'src/handlers/getUserClasses.*'
          - 'src/constants.*'
          - 'src/dynamodb/*'
          - 'src/helpers/**/*'
      environment:
        USERS_TABLE: ${self:custom.environment.USERS_TABLE}
        JWT_SECRET: ${self:custom.environment.JWT_SECRET}
      events:
        - http:
            path: /getUserClasses
            method: get
            cors: true
  editUserData:
      name: ${self:custom.base}-editUserData
      description: 'Allows the user to book a class'
      handler: src/handlers/editUserData.handler
      timeout: 30
      memorySize: 264
      package:
        patterns:
          - '!src/**'
          - 'src/handlers/editUserData.*'
          - 'src/constants.*'
          - 'src/dynamodb/*'
          - 'src/helpers/**/*'
      environment:
        USERS_TABLE: ${self:custom.environment.USERS_TABLE}
        JWT_SECRET: ${self:custom.environment.JWT_SECRET}
      events:
        - http:
            path: /editUserData
            method: post
            cors: true
  updateUserPassword:
      name: ${self:custom.base}-updateUserPassword
      description: 'Allows the user to book a class'
      handler: src/handlers/updateUserPassword.handler
      timeout: 30
      memorySize: 264
      package:
        patterns:
          - '!src/**'
          - 'src/handlers/updateUserPassword.*'
          - 'src/constants.*'
          - 'src/dynamodb/*'
          - 'src/helpers/**/*'
      environment:
        USERS_TABLE: ${self:custom.environment.USERS_TABLE}
        JWT_SECRET: ${self:custom.environment.JWT_SECRET}
      events:
        - http:
            path: /updateUserPassword
            method: post
            cors: true
  deleteUser:
      name: ${self:custom.base}-deleteUser
      description: 'Allows the user to book a class'
      handler: src/handlers/deleteUser.handler
      timeout: 30
      memorySize: 264
      package:
        patterns:
          - '!src/**'
          - 'src/handlers/deleteUser.*'
          - 'src/constants.*'
          - 'src/dynamodb/*'
          - 'src/helpers/**/*'
      environment:
        USERS_TABLE: ${self:custom.environment.USERS_TABLE}
        JWT_SECRET: ${self:custom.environment.JWT_SECRET}
      events:
        - http:
            path: /deleteUser/{userPhoneNumber}
            method: delete
            cors: true
  editPackageInfo:
      name: ${self:custom.base}-editPackageInfo
      description: 'Allows the user to book a class'
      handler: src/handlers/editPackageInfo.handler
      timeout: 30
      memorySize: 264
      package:
        patterns:
          - '!src/**'
          - 'src/handlers/editPackageInfo.*'
          - 'src/constants.*'
          - 'src/dynamodb/*'
          - 'src/helpers/**/*'
      environment:
        PACKAGES_TABLE: ${self:custom.environment.PACKAGES_TABLE}
        JWT_SECRET: ${self:custom.environment.JWT_SECRET}
      events:
        - http:
            path: /editPackageInfo
            method: post
            cors: true
  ignoreMail:
      name: ${self:custom.base}-ignoreMail
      description: 'Allows the user to book a class'
      handler: src/handlers/ignoreMail.handler
      timeout: 30
      memorySize: 264
      package:
        patterns:
          - '!src/**'
          - 'src/handlers/ignoreMail.*'
          - 'src/constants.*'
          - 'src/dynamodb/*'
          - 'src/helpers/**/*'
      environment:
        USERS_TABLE: ${self:custom.environment.USERS_TABLE}
        JWT_SECRET: ${self:custom.environment.JWT_SECRET}
      events:
        - http:
            path: /ignoreMail
            method: post
            cors: true
  sendVerificationCode:
      name: ${self:custom.base}-sendVerificationCode
      description: 'Allows the user to book a class'
      handler: src/handlers/sendVerificationCode.handler
      timeout: 30
      memorySize: 264
      package:
        patterns:
          - '!src/**'
          - 'src/handlers/sendVerificationCode.*'
          - 'src/constants.*'
          - 'src/dynamodb/*'
          - 'src/helpers/**/*'
      environment:
        USERS_TABLE: ${self:custom.environment.USERS_TABLE}
        CODES_TABLE: ${self:custom.environment.CODES_TABLE}
        JWT_SECRET: ${self:custom.environment.JWT_SECRET}
      events:
        - http:
            path: /sendVerificationCode
            method: get
            cors: true
  verifyCode:
      name: ${self:custom.base}-verifyCode
      description: 'Allows the user to book a class'
      handler: src/handlers/verifyCode.handler
      timeout: 30
      memorySize: 264
      package:
        patterns:
          - '!src/**'
          - 'src/handlers/verifyCode.*'
          - 'src/constants.*'
          - 'src/dynamodb/*'
          - 'src/helpers/**/*'
      environment:
        CODES_TABLE: ${self:custom.environment.CODES_TABLE}
        JWT_SECRET: ${self:custom.environment.JWT_SECRET}
      events:
        - http:
            path: /verifyCode
            method: post
            cors: true
  forgotPassword:
      name: ${self:custom.base}-forgotPassword
      description: 'Allows the user to book a class'
      handler: src/handlers/forgotPassword.handler
      timeout: 30
      memorySize: 264
      package:
        patterns:
          - '!src/**'
          - 'src/handlers/forgotPassword.*'
          - 'src/constants.*'
          - 'src/dynamodb/*'
          - 'src/helpers/**/*'
      environment:
        USERS_TABLE: ${self:custom.environment.USERS_TABLE}
        JWT_SECRET: ${self:custom.environment.JWT_SECRET}
      events:
        - http:
            path: /forgotPassword
            method: post
            cors: true
  